// next/src/pages/loginuser.tsx
import Router from "next/router";
import axios from "axios";
import { message } from "antd";
import { ChangeEvent, useState } from "react";

const goToReissue = () => {
  Router.push("/reissuePassword");
};

const loginUser: React.FC = () => {
  // メールアドレス
  const [mailAddress, setMailAddress] = useState<string>("");
  // パスワード
  const [password, setPassword] = useState<string>("");
  // エラーメッセージ
  const [errorMessage, setErrorMessage] = useState<string>("");
  // テキストボックス入力時に入力内容をStateに設定
  const onChangeMailAddress = (e: ChangeEvent<HTMLInputElement>) =>
    setMailAddress(e.target.value);
  // テキストボックス入力時に入力内容をStateに設定
  const onChangePassword = (e: ChangeEvent<HTMLInputElement>) =>
    setPassword(e.target.value);
  // ログイン処理
  const login = async () => {
    const res = await axios.post("http://localhost:9090/user/login", {
      email: mailAddress,
      password: password,
    });

    //コンソールに入力値・レスポンスデータを出力（確認出来たら削除する）
    console.log(mailAddress);
    console.log(password);
    console.log(res);

    //error(ログイン失敗):エラーメッセージ表示 /success(ログイン成功):ホーム画面に遷移
    if (res.data.status == "error") {
      setErrorMessage("ログインに失敗しました");
    } else {
      message.info(
        `ログイン成功! E-mail:${mailAddress}/パスワード:${password}`
      );
      setErrorMessage("");
      Router.push("/");
    }
  };

  return (
    <div className="h-screen w-screen flex flex-col gap-2 justify-center items-center">
      <div>
        <span className="mr-52 text-4xl font-semibold text-orange-500">
          Login
        </span>
      </div>

      <input
        type="text"
        onChange={onChangePassword}
        placeholder="E-mail（rakusのメールアドレス）"
        className="m-4 px-6 py-4 w-80 bg-white rounded-sm"
      />
      <input
        type="text"
        onChange={onChangeMailAddress}
        placeholder="Password（英数字8文字以上）"
        className="px-6 py-4 w-80 bg-white rounded-sm"
      />
      <button
        onClick={goToReissue}
        className="ml-40 text-sm text-gray-500 no-underline hover:underline"
      >
        パスワードを忘れた場合
      </button>
      <button
        onClick={() => {
          login();
        }}
        className="px-6 py-4 w-80 bg-orange-400 text-white text-xl text-center rounded-md hover:bg-amber-600"
      >
        ログイン
      </button>
      <div className="font-thin text-sm text-red-600">{errorMessage}</div>
    </div>
  );
};

export default loginUser;

// vue/src/views/LoginUser.vue
<template>
  <div class="w-full bg-white flex">
    <div class="w-3/5 my-20 mx-20">
      <div class="text-5xl font-semibold text-blue-500">
        How developers code is here.<br />Lets's share your experience.
      </div>
      <img class="w-96 h-96 mt-2 mx-20" :src="imageUrl" />
    </div>
    <div class="w-2/5 my-20 -ml-40">
      <div class="font-bold text-3xl m-10 -ml-4 text-blue-500">ログイン</div>
      <div class="text-red-500">{{ errorMessage }}</div>
      <div class="font-bold">メールアドレス</div>
      <div>
        <input
          type="text"
          class="p-2 m-4 w-96 border-2 rounded-xl"
          placeholder="メールアドレス"
          v-model="mailAddress"
        />
      </div>
      <div class="font-bold">パスワード</div>
      <div>
        <input
          type="text"
          class="p-2 m-4 w-96 border-2 rounded-xl"
          placeholder="パスワード"
          v-model="password"
        />
      </div>
      <button
        type="button"
        v-on:click="loginUser"
        class="bg-blue-500 rounded-lg p-2 w-48 mx-28 mt-6 text-white font-normal px-10 border-2 border-white hover:border-blue-500 hover:bg-gray-100 hover:text-blue-500"
      >
        ログイン
      </button>
    </div>
  </div>
</template>

<script lang="ts">
  import { Component, Vue } from "vue-property-decorator";
  import axios from "axios";

  @Component
  export default class RegisterUser extends Vue {
    // メールアドレス
    private mailAddress = "";
    // パスワード
    private password = "";
    // エラーメッセージ
    private errorMessage = "";
    private imageUrl = "img/engineer.png";

    async loginUser(): Promise<void> {
      const response = await axios.post(`http://localhost:8080/user/login`, {
        email: this.mailAddress,
        password: this.password,
      });

      console.log(response);

      if (response.data.status == "error") {
        this.errorMessage = "ログインに失敗しました";
      }
    }
  }
</script>
